#plantpowerjames/dotnet-test:0.0.1
apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    app: details
    service: details
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: details
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-details
  labels:
    account: details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  labels:
    app: details
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      serviceAccountName: bookinfo-details
      containers:
      - name: details
        image: plantpowerjames/dotnet-test:0.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 1000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details-service
spec:
  hosts:
  - "*"
  gateways:
  - default/ingress-gateway
  http:
  - match:
    - uri:
        exact: /weatherforecast
    route:
    - destination:
        host: details.dotnet-test.svc.cluster.local
        port:
          number: 8080