apiVersion: v1
kind: Service
metadata:
  name: dotnet-test-service
spec:
  selector:
    app: dotnet-test
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dotnet-test-details
  labels:
    account: dotnet-test