apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: workload-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: bookinfo-details
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bookinfo-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: workload-secrets
    kind: SecretStore
  target:
    name: workload-secret
    creationPolicy: Owner
  data:
  - secretKey: workload-db-username
    remoteRef:
      key: rds!cluster-df3554ce-4489-45df-a698-47c0ae0d9c06
      property: username
  - secretKey: workload-db-password
    remoteRef:
      key: rds!cluster-df3554ce-4489-45df-a698-47c0ae0d9c06
      property: password