apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: workload-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: bookinfo-details
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bookinfo-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: workload-secrets
    kind: SecretStore
  target:
    name: workload-secret
    creationPolicy: Owner
  data:
  - secretKey: workload-db-username
    remoteRef:
      key: rds!cluster-b2d693f4-46d5-4445-9891-dd3fe2d31788
      property: username
  - secretKey: workload-db-password
    remoteRef:
      key: rds!cluster-b2d693f4-46d5-4445-9891-dd3fe2d31788
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ssm-secretstore
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: bookinfo-details
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bookinfo-ssm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ssm-secretstore
    kind: SecretStore
  target:
    name: workload-ssm
    creationPolicy: Owner
  data:
  - secretKey: cluster-endpoint
    remoteRef:
      key: /aurora-serverless-sample/cluster-endpoint
  - secretKey: db-name
    remoteRef:
      key: /aurora-serverless-sample/db-name