apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    app: details
    service: details
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: details
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-details
  labels:
    account: details
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::377288124856:role/application-access-role
